GET http://localhost:8080/device/837249dd-9e7c-ad8a-9035-6b8cf5da271b/status

###

POST http://localhost:8080/device/837249dd-9e7c-ad8a-9035-6b8cf5da271b/power
Content-Type: application/json

{
  "value" : "on"
}

###

POST http://localhost:8080/device/837249dd-9e7c-ad8a-9035-6b8cf5da271b/power
Content-Type: application/json

{
  "value" : "off"
}

###

POST http://localhost:8080/device/837249dd-9e7c-ad8a-9035-6b8cf5da271b/volume
Content-Type: application/json

{
  "value" : "100"
}

###

POST http://localhost:8080/device/837249dd-9e7c-ad8a-9035-6b8cf5da271b/ac_mode
Content-Type: application/json

{
  "value" : "heat"
}

###